[build]
# Use npm ci to install exactly what's in package-lock.json
command = "npm ci && npm run build && npm run export"

# Output directory for static files
publish = "out"

# Optional: redirect all paths to index.html (for SPA routing, if needed)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
