import { describe, it, expect, afterEach, vi } from 'vitest'
import { renderWithProviders, screen, waitFor, within } from '../../test/renderWithProviders'
import { mockNavigation, resetNavigationMock } from '../../test/mockNavigation'
import type { CoreContent } from 'pliny/utils/contentlayer'
import type { Blog } from 'contentlayer/generated'
import enLocale from '@/locales/en.json'
import itLocale from '@/locales/it.json'

/**
 * Characterisation tests for `BlogListClient` — the client adapter that feeds
 * `ListWithTagsLayout` from Contentlayer's `Blog` documents.
 *
 * ## What this component actually owns
 * It is a pure prop-mapping shell: it supplies `title`/`description` from
 * `t()`, forwards `posts`/`allPosts`/`pagination`, points `getItemTags` at
 * `post.tags`, and renders each post as an `<article>` with a `<time>`, a
 * gradient title link to `/${post.path}`, a `Tag` row and a summary paragraph.
 * All filtering/paging behaviour belongs to `ListWithTagsLayout` and is
 * characterised in `layouts/ListWithTagsLayout.test.tsx`; here we assert the
 * mapping and the handful of behaviours visible only through this adapter.
 *
 * ## The bilingual field shape
 * Contentlayer flattens the bilingual front-matter into four *sibling scalar*
 * fields — `titleEn`, `titleIt`, `summaryEn`, `summaryIt` — and this component
 * selects between them with a bare ternary on `lang`:
 *
 * ```ts
 * lang === 'it' ? post.titleIt : post.titleEn
 * ```
 *
 * There is deliberately **no `?? titleEn` fallback**, unlike the `{ en, it }`
 * object fields used by `Project`. A post missing its Italian translation
 * therefore renders nothing at all under the Italian locale — pinned below.
 *
 * ## Test isolation
 * `app/blog-tag-data.json` is a build artifact regenerated by Contentlayer on
 * every content change, so it is mocked: the sidebar counts under test are the
 * fixture's, not the live blog's.
 *
 * Dates go through `Intl.DateTimeFormat(lang, { year, month: 'long', day })`,
 * whose exact output depends on the running Node build's ICU data, so only
 * stable substrings (the year) or values recomputed in the test are asserted.
 *
 * `useLanguage` applies the locale in a mount effect, so every
 * locale-dependent assertion is async.
 */

vi.mock('app/blog-tag-data.json', () => ({
  default: { opencode: 3, 'ai-agents': 2, ghost: 7 },
}))

// Imported after the tag-data mock is registered.
import BlogListClient from './BlogListClient'

const EN = enLocale
const IT = itLocale

/** Midday UTC keeps the calendar day stable across CI timezones. */
const DATE_2026 = '2026-07-22T12:00:00.000Z'
const DATE_2024 = '2024-03-15T12:00:00.000Z'

function makePost(overrides: Partial<CoreContent<Blog>> = {}): CoreContent<Blog> {
  return {
    type: 'Blog',
    title: { en: 'An OpenCode retrospective', it: 'Una retrospettiva su OpenCode' },
    summary: { en: 'English summary.', it: 'Riassunto italiano.' },
    date: DATE_2026,
    tags: [{ id: 'opencode', label: { en: 'opencode', it: 'opencode' } }],
    slug: 'opencode-retrospective',
    path: 'blog/opencode-retrospective',
    filePath: 'blog/opencode-retrospective.mdx',
    readingTime: { minutes: 6 },
    toc: [],
    titleEn: 'An OpenCode retrospective',
    titleIt: 'Una retrospettiva su OpenCode',
    summaryEn: 'What worked and what did not.',
    summaryIt: 'Cosa ha funzionato e cosa no.',
    structuredData: {},
    ...overrides,
  } as CoreContent<Blog>
}

const POST_A = makePost()
const POST_B = makePost({
  slug: 'agents-in-practice',
  path: 'blog/agents-in-practice',
  date: DATE_2024,
  titleEn: 'Agents in practice',
  titleIt: 'Agenti nella pratica',
  summaryEn: 'Notes from a year of pairing.',
  summaryIt: 'Appunti da un anno di lavoro.',
  tags: [{ id: 'ai-agents', label: { en: 'AI Agents', it: 'Agenti AI' } }],
})

interface ClientProps {
  posts: CoreContent<Blog>[]
  allPosts: CoreContent<Blog>[]
  totalPages: number
  currentPage: number
}

function renderList(overrides: Partial<ClientProps> = {}, locale: 'en' | 'it' = 'en') {
  const props: ClientProps = {
    posts: [POST_A, POST_B],
    allPosts: [POST_A, POST_B],
    totalPages: 1,
    currentPage: 1,
    ...overrides,
  }

  return renderWithProviders(<BlogListClient {...props} />, { locale })
}

/** The sidebar `<aside>` holding the "All" link and the tag list. */
function sidebar(container: HTMLElement) {
  const aside = container.querySelector('aside')
  if (!aside) throw new Error('Sidebar not found')
  return aside as HTMLElement
}

afterEach(() => {
  resetNavigationMock()
})

describe('BlogListClient', () => {
  describe('layout wiring', () => {
    it('renders the translated blog title as the level-1 heading', async () => {
      mockNavigation({ pathname: '/blog' })
      renderList()

      expect(
        await screen.findByRole('heading', { level: 1, name: EN.blog.title })
      ).toBeInTheDocument()
    })

    it('renders the translated blog description', async () => {
      mockNavigation({ pathname: '/blog' })
      renderList()

      expect(await screen.findByText(EN.blog.description)).toBeInTheDocument()
    })

    it('renders the Italian title and description under the Italian locale', async () => {
      mockNavigation({ pathname: '/blog' })
      renderList({}, 'it')

      expect(await screen.findByText(IT.blog.description)).toBeInTheDocument()
      expect(screen.getByRole('heading', { level: 1, name: IT.blog.title })).toBeInTheDocument()
    })

    it('uses the default vertical list layout rather than a grid', async () => {
      mockNavigation({ pathname: '/blog' })
      const { container } = renderList()

      await screen.findByRole('heading', { level: 1 })
      const column = container.querySelector('div.flex-1')
      expect(column?.className).toContain('space-y-6')
      expect(column?.className).not.toContain('grid-cols-1')
    })

    it('renders one article per post', async () => {
      mockNavigation({ pathname: '/blog' })
      const { container } = renderList()

      await screen.findByRole('heading', { level: 1 })
      expect(container.querySelectorAll('article')).toHaveLength(2)
    })
  })

  describe('mocked tag data', () => {
    it('renders sidebar counts from the mocked tag data, not live content', async () => {
      mockNavigation({ pathname: '/blog' })
      const { container } = renderList()

      await waitFor(() =>
        expect(within(sidebar(container)).getByText('opencode (3)')).toBeInTheDocument()
      )
      expect(within(sidebar(container)).getByText('AI Agents (2)')).toBeInTheDocument()
    })

    it('skips mocked tag ids that no post carries', async () => {
      mockNavigation({ pathname: '/blog' })
      const { container } = renderList()

      await screen.findByRole('heading', { level: 1 })
      expect(within(sidebar(container)).queryByText(/ghost/)).not.toBeInTheDocument()
      expect(within(sidebar(container)).getAllByRole('listitem')).toHaveLength(2)
    })

    it('renders the Italian tag labels under the Italian locale', async () => {
      mockNavigation({ pathname: '/blog' })
      const { container } = renderList({}, 'it')

      await waitFor(() =>
        expect(within(sidebar(container)).getByText('Agenti AI (2)')).toBeInTheDocument()
      )
    })
  })

  describe('title field mapping', () => {
    it('renders titleEn under the English locale', async () => {
      mockNavigation({ pathname: '/blog' })
      renderList()

      expect(await screen.findByText('An OpenCode retrospective')).toBeInTheDocument()
      expect(screen.queryByText('Una retrospettiva su OpenCode')).not.toBeInTheDocument()
    })

    it('renders titleIt under the Italian locale', async () => {
      mockNavigation({ pathname: '/blog' })
      renderList({}, 'it')

      expect(await screen.findByText('Una retrospettiva su OpenCode')).toBeInTheDocument()
      expect(screen.queryByText('An OpenCode retrospective')).not.toBeInTheDocument()
    })

    it('ignores the bilingual title object in favour of the flattened fields', async () => {
      mockNavigation({ pathname: '/blog' })
      renderList({
        posts: [
          makePost({
            title: { en: 'Object title', it: 'Titolo oggetto' },
            titleEn: 'Flattened title',
          }),
        ],
        allPosts: [makePost({ titleEn: 'Flattened title' })],
      })

      expect(await screen.findByText('Flattened title')).toBeInTheDocument()
      expect(screen.queryByText('Object title')).not.toBeInTheDocument()
    })

    it('renders the title inside a level-2 heading', async () => {
      mockNavigation({ pathname: '/blog' })
      renderList({ posts: [POST_A], allPosts: [POST_A] })

      expect(
        await screen.findByRole('heading', { level: 2, name: 'An OpenCode retrospective' })
      ).toBeInTheDocument()
    })

    it('links the title to /${post.path}', async () => {
      mockNavigation({ pathname: '/blog' })
      renderList({ posts: [POST_A], allPosts: [POST_A] })

      const link = await screen.findByRole('link', { name: 'An OpenCode retrospective' })
      expect(link).toHaveAttribute('href', '/blog/opencode-retrospective')
    })

    it('builds the href from path, not from slug', async () => {
      mockNavigation({ pathname: '/blog' })
      const post = makePost({ slug: 'not-used', path: 'blog/nested/real-path' })
      renderList({ posts: [post], allPosts: [post] })

      const link = await screen.findByRole('link', { name: 'An OpenCode retrospective' })
      expect(link).toHaveAttribute('href', '/blog/nested/real-path')
    })

    /**
     * FINDING — no English fallback on the flattened bilingual fields.
     *
     * `ProjectHeader` resolves its `{ en, it }` object fields as
     * `field?.[lang] ?? field?.en`, but `BlogListClient` uses a bare ternary on
     * the flattened scalars. A post whose Italian translation is missing
     * therefore renders an **empty** title/summary under `it` instead of
     * falling back to English.
     */
    it('renders an empty title when titleIt is missing under the Italian locale', async () => {
      mockNavigation({ pathname: '/blog' })
      const post = makePost({
        titleEn: 'English only title',
        titleIt: undefined as unknown as string,
      })
      renderList({ posts: [post], allPosts: [post] }, 'it')

      // The Italian description proves the locale has been applied.
      await screen.findByText(IT.blog.description)
      expect(screen.queryByText('English only title')).not.toBeInTheDocument()
      expect(screen.getByRole('heading', { level: 2 })).toHaveTextContent('')
    })
  })

  describe('summary field mapping', () => {
    it('renders summaryEn under the English locale', async () => {
      mockNavigation({ pathname: '/blog' })
      renderList({ posts: [POST_A], allPosts: [POST_A] })

      expect(await screen.findByText('What worked and what did not.')).toBeInTheDocument()
      expect(screen.queryByText('Cosa ha funzionato e cosa no.')).not.toBeInTheDocument()
    })

    it('renders summaryIt under the Italian locale', async () => {
      mockNavigation({ pathname: '/blog' })
      renderList({ posts: [POST_A], allPosts: [POST_A] }, 'it')

      expect(await screen.findByText('Cosa ha funzionato e cosa no.')).toBeInTheDocument()
      expect(screen.queryByText('What worked and what did not.')).not.toBeInTheDocument()
    })

    it('ignores the bilingual summary object in favour of the flattened fields', async () => {
      mockNavigation({ pathname: '/blog' })
      const post = makePost({
        summary: { en: 'Object summary.', it: 'Riassunto oggetto.' },
        summaryEn: 'Flattened summary.',
      })
      renderList({ posts: [post], allPosts: [post] })

      expect(await screen.findByText('Flattened summary.')).toBeInTheDocument()
      expect(screen.queryByText('Object summary.')).not.toBeInTheDocument()
    })

    it('renders an empty summary when summaryIt is missing under the Italian locale', async () => {
      mockNavigation({ pathname: '/blog' })
      const post = makePost({
        summaryEn: 'English only summary.',
        summaryIt: undefined as unknown as string,
      })
      renderList({ posts: [post], allPosts: [post] }, 'it')

      await screen.findByText(IT.blog.description)
      expect(screen.queryByText('English only summary.')).not.toBeInTheDocument()
    })

    it('maps title and summary independently per post', async () => {
      mockNavigation({ pathname: '/blog' })
      renderList({}, 'it')

      expect(await screen.findByText('Una retrospettiva su OpenCode')).toBeInTheDocument()
      expect(screen.getByText('Agenti nella pratica')).toBeInTheDocument()
      expect(screen.getByText('Cosa ha funzionato e cosa no.')).toBeInTheDocument()
      expect(screen.getByText('Appunti da un anno di lavoro.')).toBeInTheDocument()
    })
  })

  describe('date formatting', () => {
    it('renders the date inside a machine-readable <time dateTime>', async () => {
      mockNavigation({ pathname: '/blog' })
      const { container } = renderList({ posts: [POST_A], allPosts: [POST_A] })

      await screen.findByRole('heading', { level: 1 })
      const time = container.querySelector('time')
      expect(time).toHaveAttribute('datetime', DATE_2026)
    })

    it('renders the year under the English locale', async () => {
      mockNavigation({ pathname: '/blog' })
      const { container } = renderList({ posts: [POST_A], allPosts: [POST_A] })

      await screen.findByRole('heading', { level: 1 })
      expect(container.querySelector('time')).toHaveTextContent('2026')
    })

    it('formats the date with Intl under the English locale', async () => {
      mockNavigation({ pathname: '/blog' })
      renderList({ posts: [POST_A], allPosts: [POST_A] })

      const expected = new Intl.DateTimeFormat('en', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      }).format(new Date(DATE_2026))
      expect(await screen.findByText(expected)).toBeInTheDocument()
    })

    it('formats the date with Intl under the Italian locale', async () => {
      mockNavigation({ pathname: '/blog' })
      renderList({ posts: [POST_A], allPosts: [POST_A] }, 'it')

      const expected = new Intl.DateTimeFormat('it', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      }).format(new Date(DATE_2026))
      expect(await screen.findByText(expected)).toBeInTheDocument()
    })

    it('produces different output per locale for the same timestamp', async () => {
      const enText = new Intl.DateTimeFormat('en', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      }).format(new Date(DATE_2026))
      const itText = new Intl.DateTimeFormat('it', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      }).format(new Date(DATE_2026))
      // Guards the locale-sensitivity assertions above against an ICU-less
      // Node build, where both would collapse to the same string.
      expect(enText).not.toBe(itText)
    })

    it('formats each post with its own date', async () => {
      mockNavigation({ pathname: '/blog' })
      const { container } = renderList()

      await screen.findByRole('heading', { level: 1 })
      const times = Array.from(container.querySelectorAll('time'))
      expect(times.map((time) => time.getAttribute('datetime'))).toEqual([DATE_2026, DATE_2024])
      expect(times[1]).toHaveTextContent('2024')
    })
  })

  describe('tag row', () => {
    it('renders a Tag per post tag with the English label', async () => {
      mockNavigation({ pathname: '/blog' })
      const { container } = renderList({ posts: [POST_B], allPosts: [POST_B] })

      await screen.findByRole('heading', { level: 1 })
      const article = container.querySelector('article')
      expect(within(article as HTMLElement).getByText('AI Agents')).toBeInTheDocument()
    })

    it('renders the Italian tag label under the Italian locale', async () => {
      mockNavigation({ pathname: '/blog' })
      const { container } = renderList({ posts: [POST_B], allPosts: [POST_B] }, 'it')

      await waitFor(() => {
        const article = container.querySelector('article')
        expect(within(article as HTMLElement).getByText('Agenti AI')).toBeInTheDocument()
      })
    })

    it('renders no tags inside the article when the post has none', async () => {
      mockNavigation({ pathname: '/blog' })
      const post = makePost({ tags: [] })
      const { container } = renderList({ posts: [post], allPosts: [post] })

      await screen.findByRole('heading', { level: 1 })
      const article = container.querySelector('article')
      // Only the heading link; no tag spans.
      expect(within(article as HTMLElement).queryByText('opencode')).not.toBeInTheDocument()
    })

    it('does not throw when a post has no tags field at all', async () => {
      mockNavigation({ pathname: '/blog' })
      const post = makePost({ tags: undefined })
      renderList({ posts: [post], allPosts: [post] })

      expect(await screen.findByRole('heading', { level: 1 })).toBeInTheDocument()
    })
  })

  describe('filtering delegated to the layout', () => {
    it('filters the list by the ?tag= query parameter', async () => {
      mockNavigation({ pathname: '/blog', searchParams: { tag: 'ai-agents' } })
      renderList()

      expect(await screen.findByText('Agents in practice')).toBeInTheDocument()
      expect(screen.queryByText('An OpenCode retrospective')).not.toBeInTheDocument()
    })

    it('renders the layout empty state when no post carries the tag', async () => {
      mockNavigation({ pathname: '/blog', searchParams: { tag: 'ghost' } })
      renderList()

      expect(await screen.findByText('No items found.')).toBeInTheDocument()
    })

    it('passes allPosts so filtering sees posts outside the current page', async () => {
      mockNavigation({ pathname: '/blog', searchParams: { tag: 'ai-agents' } })
      // `posts` holds only the first page, but `allPosts` holds both.
      renderList({ posts: [POST_A], allPosts: [POST_A, POST_B] })

      expect(await screen.findByText('Agents in practice')).toBeInTheDocument()
    })
  })

  describe('pagination delegated to the layout', () => {
    it('renders the pagination nav when the list spans more than one page', async () => {
      mockNavigation({ pathname: '/blog' })
      renderList({ totalPages: 2 })

      await screen.findByRole('heading', { level: 1 })
      expect(screen.getByRole('navigation')).toHaveTextContent('1 / 2')
    })

    it('renders no nav for a single-page list', async () => {
      mockNavigation({ pathname: '/blog' })
      renderList({ totalPages: 1 })

      await screen.findByRole('heading', { level: 1 })
      expect(screen.queryByRole('navigation')).not.toBeInTheDocument()
    })

    it('slices the page from the pathname, not from the currentPage prop', async () => {
      mockNavigation({ pathname: '/blog/page/2' })
      // pageSize = ceil(2 / 2) = 1 → page 2 is the second post.
      renderList({ totalPages: 2, currentPage: 1 })

      expect(await screen.findByText('Agents in practice')).toBeInTheDocument()
      expect(screen.queryByText('An OpenCode retrospective')).not.toBeInTheDocument()
    })

    it('renders the translated next link', async () => {
      mockNavigation({ pathname: '/blog' })
      renderList({ totalPages: 2 }, 'it')

      const next = await screen.findByRole('link', { name: `${IT.common.next} →` })
      expect(next).toHaveAttribute('href', '/blog/page/2')
    })
  })

  describe('empty input', () => {
    it('renders the empty state when there are no posts', async () => {
      mockNavigation({ pathname: '/blog' })
      renderList({ posts: [], allPosts: [], totalPages: 0 })

      expect(await screen.findByText('No items found.')).toBeInTheDocument()
    })

    it('still renders the title and the "All" sidebar link with no posts', async () => {
      mockNavigation({ pathname: '/blog' })
      const { container } = renderList({ posts: [], allPosts: [], totalPages: 0 })

      await screen.findByRole('heading', { level: 1, name: EN.blog.title })
      expect(within(sidebar(container)).getByRole('link', { name: EN.common.all })).toHaveAttribute(
        'href',
        '/blog'
      )
    })

    it('renders no tag list items when there are no posts to resolve labels from', async () => {
      mockNavigation({ pathname: '/blog' })
      const { container } = renderList({ posts: [], allPosts: [], totalPages: 0 })

      await screen.findByRole('heading', { level: 1 })
      expect(within(sidebar(container)).queryAllByRole('listitem')).toHaveLength(0)
    })
  })
})
