import { describe, it, expect, afterEach, vi } from 'vitest'
import { renderWithProviders, screen, waitFor, within } from '../../test/renderWithProviders'
import { mockNavigation, resetNavigationMock } from '../../test/mockNavigation'
import type { CoreContent } from 'pliny/utils/contentlayer'
import type { Project } from 'contentlayer/generated'
import enLocale from '@/locales/en.json'
import itLocale from '@/locales/it.json'

/**
 * Characterisation tests for `ProjectsListClient` — the client adapter that
 * feeds `ListWithTagsLayout` from Contentlayer's `Project` documents.
 *
 * ## What this component actually owns
 * Four decisions, all asserted below:
 *
 * 1. `contentLayout="grid"`, so the content column gets the responsive grid
 *    classes instead of the default vertical `space-y-6`.
 * 2. `items` **and** `allItems` are both the same `projects` array — this list
 *    has no `pagination` prop at all, so every project always renders and no
 *    pagination nav is ever produced.
 * 3. Unlike `BlogListClient`'s flattened `titleEn`/`titleIt` scalars, projects
 *    keep bilingual **objects** and are resolved with a real fallback:
 *    `project.title?.[lang] ?? project.title?.en`.
 * 4. `priority` (which becomes `fetchpriority="high"` on the cover image) is
 *    set only when `projects.findIndex((p) => p.slug === project.slug) === 0`
 *    — i.e. on the first project only.
 *
 * ## The findIndex-by-slug detail
 * The index is recomputed per render via `findIndex` on `slug` rather than
 * taken from `renderItem`'s position, so it is the first project *in the
 * `projects` prop* that gets priority — and duplicate slugs collapse onto the
 * same index. Both are pinned below.
 *
 * ## Test isolation
 * `app/project-tag-data.json` is a build artifact regenerated by Contentlayer
 * on every content change, so it is mocked: the sidebar counts under test are
 * the fixture's, not the live project set's.
 *
 * `useLanguage` applies the locale in a mount effect, so every
 * locale-dependent assertion is async.
 */

vi.mock('app/project-tag-data.json', () => ({
  default: { nextjs: 4, ios: 2, ghost: 9 },
}))

// Imported after the tag-data mock is registered.
import ProjectsListClient from './ProjectsListClient'

const EN = enLocale
const IT = itLocale

/** Midday UTC keeps the calendar month stable across CI timezones. */
const DATE = '2026-07-22T12:00:00.000Z'
/** A `/static/images/*.png` src makes `Image` take its `<picture>` branch. */
const COVER = '/static/images/projects/certflow.png'

function makeProject(overrides: Partial<CoreContent<Project>> = {}): CoreContent<Project> {
  return {
    type: 'Project',
    title: { en: 'CertFlow', it: 'CertFlow IT' },
    summary: { en: 'English summary.', it: 'Riassunto italiano.' },
    date: DATE,
    tags: [{ id: 'nextjs', label: { en: 'Next.js', it: 'Next.js' } }],
    stack: [],
    coverImage: COVER,
    projectType: undefined,
    status: undefined,
    links: undefined,
    readingTime: { minutes: 4 },
    slug: 'certflow',
    path: 'projects/certflow',
    filePath: 'projects/certflow.mdx',
    titleEn: 'CertFlow',
    summaryEn: 'English summary.',
    structuredData: {},
    ...overrides,
  } as CoreContent<Project>
}

const PROJECT_A = makeProject()
const PROJECT_B = makeProject({
  slug: 'micelio',
  path: 'projects/micelio',
  title: { en: 'Micelio', it: 'Micelio IT' },
  summary: { en: 'Second summary.', it: 'Secondo riassunto.' },
  coverImage: '/static/images/projects/micelio.png',
  tags: [{ id: 'ios', label: { en: 'iOS', it: 'iOS' } }],
})
const PROJECT_C = makeProject({
  slug: 'blog-writer',
  path: 'projects/blog-writer',
  title: { en: 'Blog-Writer', it: 'Blog-Writer IT' },
  summary: { en: 'Third summary.', it: 'Terzo riassunto.' },
  coverImage: '/static/images/projects/blog-writer.png',
  tags: [{ id: 'nextjs', label: { en: 'Next.js', it: 'Next.js' } }],
})

function renderList(
  projects: CoreContent<Project>[] = [PROJECT_A, PROJECT_B],
  locale: 'en' | 'it' = 'en'
) {
  return renderWithProviders(<ProjectsListClient projects={projects} />, { locale })
}

/** The sidebar `<aside>` holding the "All" link and the tag list. */
function sidebar(container: HTMLElement) {
  const aside = container.querySelector('aside')
  if (!aside) throw new Error('Sidebar not found')
  return aside as HTMLElement
}

/** The `flex-1` content column that holds the cards. */
function contentColumn(container: HTMLElement) {
  const column = container.querySelector('div.flex-1')
  if (!column) throw new Error('Content column not found')
  return column as HTMLElement
}

/** Every rendered cover image, in document order. */
function coverImages(container: HTMLElement) {
  return Array.from(container.querySelectorAll('img'))
}

afterEach(() => {
  resetNavigationMock()
})

describe('ProjectsListClient', () => {
  describe('layout wiring', () => {
    it('renders the translated projects title as the level-1 heading', async () => {
      mockNavigation({ pathname: '/projects' })
      renderList()

      expect(
        await screen.findByRole('heading', { level: 1, name: EN.projects.title })
      ).toBeInTheDocument()
    })

    it('renders the translated projects description', async () => {
      mockNavigation({ pathname: '/projects' })
      renderList()

      expect(await screen.findByText(EN.projects.description)).toBeInTheDocument()
    })

    it('renders the Italian title and description under the Italian locale', async () => {
      mockNavigation({ pathname: '/projects' })
      renderList([PROJECT_A, PROJECT_B], 'it')

      expect(await screen.findByText(IT.projects.description)).toBeInTheDocument()
      expect(screen.getByRole('heading', { level: 1, name: IT.projects.title })).toBeInTheDocument()
      expect(IT.projects.title).toBe('Progetti')
    })
  })

  describe('grid content layout', () => {
    it('applies the responsive grid classes to the content column', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList()

      await screen.findByRole('heading', { level: 1 })
      const className = contentColumn(container).className
      expect(className).toContain('grid')
      expect(className).toContain('grid-cols-1')
      expect(className).toContain('sm:grid-cols-2')
    })

    it('does not apply the vertical list spacing used by the blog list', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList()

      await screen.findByRole('heading', { level: 1 })
      expect(contentColumn(container).className).not.toContain('space-y-6')
    })

    it('renders one card article per project', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList([PROJECT_A, PROJECT_B, PROJECT_C])

      await screen.findByRole('heading', { level: 1 })
      expect(container.querySelectorAll('article')).toHaveLength(3)
    })
  })

  describe('priority on the first project only', () => {
    it('marks the first project’s cover image as high fetch priority', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList([PROJECT_A, PROJECT_B, PROJECT_C])

      await screen.findByRole('heading', { level: 1 })
      expect(coverImages(container)[0]).toHaveAttribute('fetchpriority', 'high')
    })

    it('leaves every later cover image at auto priority', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList([PROJECT_A, PROJECT_B, PROJECT_C])

      await screen.findByRole('heading', { level: 1 })
      const priorities = coverImages(container).map((img) => img.getAttribute('fetchpriority'))
      expect(priorities).toEqual(['high', 'auto', 'auto'])
    })

    it('sets priority on exactly one image', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList([PROJECT_A, PROJECT_B, PROJECT_C])

      await screen.findByRole('heading', { level: 1 })
      expect(
        coverImages(container).filter((img) => img.getAttribute('fetchpriority') === 'high')
      ).toHaveLength(1)
    })

    it('gives the single project priority when the list has one entry', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList([PROJECT_A])

      await screen.findByRole('heading', { level: 1 })
      expect(coverImages(container)[0]).toHaveAttribute('fetchpriority', 'high')
    })

    it('follows the order of the projects prop, not alphabetical order', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList([PROJECT_B, PROJECT_A])

      await screen.findByRole('heading', { level: 1 })
      const priorities = coverImages(container).map((img) => img.getAttribute('fetchpriority'))
      expect(priorities).toEqual(['high', 'auto'])
      // `micelio` is now first, so it is the one that gets priority.
      expect(coverImages(container)[0]).toHaveAttribute('alt', 'Micelio')
    })

    /**
     * FINDING — the priority index is resolved with
     * `projects.findIndex((p) => p.slug === project.slug)` rather than from the
     * render position. Two projects sharing a slug therefore both resolve to
     * index 0 and both receive `priority`, defeating the single-LCP-hint intent.
     */
    it('marks both cards when two projects share the first slug', async () => {
      mockNavigation({ pathname: '/projects' })
      const duplicate = makeProject({
        path: 'projects/certflow-duplicate',
        title: { en: 'CertFlow duplicate', it: 'CertFlow duplicato' },
        coverImage: '/static/images/projects/duplicate.png',
      })
      // The cards are keyed on `slug` too, so React also warns about the
      // duplicate key. That is part of the same defect; silence it so the
      // suite stays quiet without hiding the assertion.
      const consoleError = vi.spyOn(console, 'error').mockImplementation(() => {})
      const { container } = renderList([PROJECT_A, duplicate])

      await screen.findByRole('heading', { level: 1 })
      const priorities = coverImages(container).map((img) => img.getAttribute('fetchpriority'))
      expect(priorities).toEqual(['high', 'high'])
      expect(consoleError).toHaveBeenCalled()
      consoleError.mockRestore()
    })

    it('gives no card priority when the first project has no cover image', async () => {
      mockNavigation({ pathname: '/projects' })
      const noCover = makeProject({ coverImage: undefined })
      const { container } = renderList([noCover, PROJECT_B])

      await screen.findByRole('heading', { level: 1 })
      // The priority flag rides on the cover image, which is not rendered.
      const priorities = coverImages(container).map((img) => img.getAttribute('fetchpriority'))
      expect(priorities).toEqual(['auto'])
    })

    it('keeps priority on the first project after a tag filter reorders the visible set', async () => {
      mockNavigation({ pathname: '/projects', searchParams: { tag: 'ios' } })
      const { container } = renderList([PROJECT_A, PROJECT_B])

      await screen.findByRole('heading', { level: 1 })
      // Only `micelio` survives the filter, but the index is computed against
      // the full `projects` prop, where it sits at position 1 — so the single
      // visible card gets no priority at all.
      expect(coverImages(container)).toHaveLength(1)
      expect(coverImages(container)[0]).toHaveAttribute('fetchpriority', 'auto')
    })
  })

  describe('bilingual title and summary resolution', () => {
    it('renders the English title and summary under the English locale', async () => {
      mockNavigation({ pathname: '/projects' })
      renderList([PROJECT_A])

      expect(await screen.findByRole('heading', { level: 2, name: 'CertFlow' })).toBeInTheDocument()
      expect(screen.getByText('English summary.')).toBeInTheDocument()
    })

    it('renders the Italian title and summary under the Italian locale', async () => {
      mockNavigation({ pathname: '/projects' })
      renderList([PROJECT_A], 'it')

      expect(
        await screen.findByRole('heading', { level: 2, name: 'CertFlow IT' })
      ).toBeInTheDocument()
      expect(screen.getByText('Riassunto italiano.')).toBeInTheDocument()
    })

    it('falls back to the English title when the Italian one is missing', async () => {
      mockNavigation({ pathname: '/projects' })
      const project = makeProject({ title: { en: 'English only title' } as Project['title'] })
      renderList([project], 'it')

      // Unlike `BlogListClient`, projects have a real `?? title?.en` fallback.
      expect(
        await screen.findByRole('heading', { level: 2, name: 'English only title' })
      ).toBeInTheDocument()
    })

    it('falls back to the English summary when the Italian one is missing', async () => {
      mockNavigation({ pathname: '/projects' })
      const project = makeProject({
        summary: { en: 'English only summary.' } as Project['summary'],
      })
      renderList([project], 'it')

      expect(await screen.findByText('English only summary.')).toBeInTheDocument()
    })

    /**
     * FINDING — a project with no `title` at all resolves to `undefined`, which
     * is forwarded to the cover image's `alt`. `next/image` warns
     * ("Image is missing required \"alt\" property") and the card renders an
     * unlabelled image. Neither `ProjectsListClient` nor `ProjectCardBase`
     * guards against this.
     */
    it('renders an unlabelled image when title and summary are absent entirely', async () => {
      mockNavigation({ pathname: '/projects' })
      const project = makeProject({ title: undefined, summary: undefined })
      const consoleError = vi.spyOn(console, 'error').mockImplementation(() => {})
      const { container } = renderList([project])

      expect(await screen.findByRole('heading', { level: 1 })).toBeInTheDocument()
      expect(container.querySelector('img')).not.toHaveAttribute('alt')
      expect(consoleError).toHaveBeenCalled()
      consoleError.mockRestore()
    })

    it('does not throw when title and summary are absent and there is no cover image', async () => {
      mockNavigation({ pathname: '/projects' })
      const project = makeProject({ title: undefined, summary: undefined, coverImage: undefined })
      renderList([project])

      expect(await screen.findByRole('heading', { level: 1 })).toBeInTheDocument()
      expect(screen.getByRole('heading', { level: 2 })).toHaveTextContent('')
    })

    it('links each card to /projects/${slug}', async () => {
      mockNavigation({ pathname: '/projects' })
      renderList([PROJECT_B])

      const link = await screen.findByRole('heading', { level: 2, name: 'Micelio' })
      expect(within(link).getByRole('link')).toHaveAttribute('href', '/projects/micelio')
    })

    it('builds the href from slug, not from path', async () => {
      mockNavigation({ pathname: '/projects' })
      const project = makeProject({ slug: 'real-slug', path: 'projects/nested/other' })
      renderList([project])

      const heading = await screen.findByRole('heading', { level: 2, name: 'CertFlow' })
      expect(within(heading).getByRole('link')).toHaveAttribute('href', '/projects/real-slug')
    })
  })

  describe('card metadata', () => {
    it('renders the cover image with the resolved title as alt text', async () => {
      mockNavigation({ pathname: '/projects' })
      renderList([PROJECT_A], 'it')

      expect(await screen.findByRole('img', { name: 'CertFlow IT' })).toBeInTheDocument()
    })

    it('renders the date badge as a machine-readable <time>', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList([PROJECT_A])

      await screen.findByRole('heading', { level: 1 })
      expect(container.querySelector('time')).toHaveAttribute('datetime', DATE)
    })

    it('renders the year in the date badge', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList([PROJECT_A])

      await screen.findByRole('heading', { level: 1 })
      expect(container.querySelector('time')).toHaveTextContent('2026')
    })

    it('renders the project tags inside the card', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList([PROJECT_B])

      await screen.findByRole('heading', { level: 1 })
      const article = container.querySelector('article')
      expect(within(article as HTMLElement).getByText('iOS')).toBeInTheDocument()
    })

    it('does not throw when a project has no tags', async () => {
      mockNavigation({ pathname: '/projects' })
      const project = makeProject({ tags: undefined })
      renderList([project])

      expect(await screen.findByRole('heading', { level: 1 })).toBeInTheDocument()
    })
  })

  describe('mocked tag data', () => {
    it('renders sidebar counts from the mocked tag data, not live content', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList()

      await waitFor(() =>
        expect(within(sidebar(container)).getByText('Next.js (4)')).toBeInTheDocument()
      )
      expect(within(sidebar(container)).getByText('iOS (2)')).toBeInTheDocument()
    })

    it('skips mocked tag ids that no project carries', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList()

      await screen.findByRole('heading', { level: 1 })
      expect(within(sidebar(container)).queryByText(/ghost/)).not.toBeInTheDocument()
      expect(within(sidebar(container)).getAllByRole('listitem')).toHaveLength(2)
    })

    it('points the "All" link at the projects base path', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList()

      const link = await within(sidebar(container)).findByRole('link', { name: EN.common.all })
      expect(link).toHaveAttribute('href', '/projects')
    })

    it('builds tag hrefs from the projects pathname', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList()

      const link = await within(sidebar(container)).findByRole('link', { name: 'iOS (2)' })
      expect(link).toHaveAttribute('href', '/projects?tag=ios')
    })
  })

  describe('filtering delegated to the layout', () => {
    it('filters the grid by the ?tag= query parameter', async () => {
      mockNavigation({ pathname: '/projects', searchParams: { tag: 'ios' } })
      renderList([PROJECT_A, PROJECT_B])

      expect(await screen.findByRole('heading', { level: 2, name: 'Micelio' })).toBeInTheDocument()
      expect(screen.queryByRole('heading', { level: 2, name: 'CertFlow' })).not.toBeInTheDocument()
    })

    it('keeps every project sharing the active tag', async () => {
      mockNavigation({ pathname: '/projects', searchParams: { tag: 'nextjs' } })
      const { container } = renderList([PROJECT_A, PROJECT_B, PROJECT_C])

      await screen.findByRole('heading', { level: 1 })
      expect(container.querySelectorAll('article')).toHaveLength(2)
    })

    it('renders the layout empty state when no project carries the tag', async () => {
      mockNavigation({ pathname: '/projects', searchParams: { tag: 'ghost' } })
      renderList()

      expect(await screen.findByText('No items found.')).toBeInTheDocument()
    })
  })

  describe('no pagination', () => {
    it('never renders a pagination nav, however many projects there are', async () => {
      mockNavigation({ pathname: '/projects' })
      renderList([PROJECT_A, PROJECT_B, PROJECT_C])

      await screen.findByRole('heading', { level: 1 })
      expect(screen.queryByRole('navigation')).not.toBeInTheDocument()
    })

    it('renders every project rather than slicing a page', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList([PROJECT_A, PROJECT_B, PROJECT_C])

      await screen.findByRole('heading', { level: 1 })
      expect(container.querySelectorAll('article')).toHaveLength(3)
    })

    it('ignores a /page/N pathname entirely', async () => {
      mockNavigation({ pathname: '/projects/page/2' })
      const { container } = renderList([PROJECT_A, PROJECT_B, PROJECT_C])

      await screen.findByRole('heading', { level: 1 })
      // With no `pagination` prop, `pageSize` is null and slicing is skipped.
      expect(container.querySelectorAll('article')).toHaveLength(3)
      expect(screen.queryByRole('navigation')).not.toBeInTheDocument()
    })
  })

  describe('empty input', () => {
    it('renders the empty state when there are no projects', async () => {
      mockNavigation({ pathname: '/projects' })
      renderList([])

      expect(await screen.findByText('No items found.')).toBeInTheDocument()
    })

    it('still renders the title and the "All" sidebar link with no projects', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList([])

      await screen.findByRole('heading', { level: 1, name: EN.projects.title })
      expect(
        within(sidebar(container)).getByRole('link', { name: EN.common.all })
      ).toBeInTheDocument()
    })

    it('renders no tag list items when there are no projects to resolve labels from', async () => {
      mockNavigation({ pathname: '/projects' })
      const { container } = renderList([])

      await screen.findByRole('heading', { level: 1 })
      expect(within(sidebar(container)).queryAllByRole('listitem')).toHaveLength(0)
    })
  })
})
